<?php

class Solvingmagento_Downloadkeys_Model_Uploader extends Mage_Core_Model_Abstract
{
    protected $_state;
    protected $_session;
    protected $_parts = array();
    
    /**
     *
     * @param type $key parameters of the post request generated by the step 2 insert key data
     */
    public function setData($key, $value=null)
    {
        parent::setData($key);
        $this->_parts = Solvingmagento_Downloadkeys_Model_Downloadkey::populateKeyParts($key); 
    }
    
    /**
     * overriding the costruct method to initialize session access
     */
     public function __construct()
    {
        parent::__construct();
        $this->_session = Mage::getSingleton('adminhtml/session');
        $this->_state = true;
    }
    
    /**
     * validates key captions and key entries
     * @return boolean flag to indicate the validation result
     */
    public function validate()
    {
        $this->_validateCaptions();
        $this->_validateKeyParts();
        return $this->_state;
    }
    
    protected function _validateCaptions()
    {
        foreach ($this->_parts as $part) {
            if (strlen(trim($part['caption'])) <= 0) {
                $this->_session->addError(
                    Mage::helper('downloadkeys')->__(
                        'Empty caption for key part %s',
                        $part['part_num']
                    )
                );
                $this->_state = false;
            }
        }
    }
    
    protected function _validateKeyParts()
    {
        foreach ($this->_parts as $part) {
            if (sizeof($part['key_entries']) <= 0) {
                $this->_session->addError(
                    Mage::helper('downloadkeys')->__(
                        'No key data provided for part %s',
                        $part['part_num']
                    )
                );
                $this->_state = false;
            }
            
            if (sizeof($part['key_entries']) != sizeof($this->_parts[0]['key_entries'])) {
                $this->_session->addError(
                    Mage::helper('downloadkeys')->__(
                        'Number of key entries in part %d is not equal to that of part 1',
                        $part['part_num']
                    )
                );
                $this->_state = false;
            }
        }
    }
    
    public function getPreviewData()
    {
        $entriesNum = 3;
        
        if (sizeof($this->_parts[0]['key_entries']) < 3) {
            $entriesNum = sizeof($this->_parts[0]['key_entries']);
        }
        
        $previewData = array();
        
        foreach ($this->_parts as $part) {
            $keyEntries = array();
            
            for ($i = 0; $i < $entriesNum; $i++) {
                $keyEntries[] = $part['key_entries'][$i];
            }
            $previewData[] = array(
                'part_num'  =>  $part['part_num'],
                'caption'   =>  $part['caption'],
                'key_entries'   =>  $keyEntries
            );
        }
              
        return $previewData;
    }
    
    public function getKeyData() 
    {
        return $this->_parts;
    }
    
}
?>
